### ISSUE TITLE
Support for Fine Offset WH1080/WH1081

### ISSUE THREAD

**Issue by maaw** [merbanan/rtl_433#133] opened 2015-07-19 14:17 UTC
Hi, this is an extremely popular weather station, with a very crappy receiver. Could you please add support for this one? How can I help you?
It seems like another guy wrote an application to support the wh1081 here: https://github.com/jimstudt/ook-decoder
But i cannot get it to work.
Thank you for your time :)
Regards

**Comment by rct** [comment] 2015-07-20 16:43
First, you can probably get more help in the rtl_433 google group.

The next step would be to record some sample signals using rtl_433 -p NNN -a -t and to note what readings they correspond to (tempeature, humdity, wind speed, direction, etc.)

You might have to lower the signal detection threshold with -l 5000 or so.    By default it is 10,000 which is ok if the device is fairly close or you have a good antenna.

Also make sure you figure our your rtl_433 stick's frequency offset (PPM error) to make sure you are listening on the right frequency.

**Comment by maaw** [comment] 2015-07-20 19:52
Thank you very much for your answer @rct. I don't have access to the group. How can i

**Comment by rct** [comment] 2015-07-21 16:22
The google group rtl_433 can be found at: http://groups.google.com/group/rtl_433.

I see you closed this issue, hopefully you will still see this response.  I think you should have left this open until there was support for this weather station.

**Comment by maaw** [comment] 2015-07-21 16:39
Sorry and thank you for your answer. I signed up to the group and found nothing related, so I guess I'll have to do some research before posting.
I'm not sure how I closed the issue.
Again thank you for your attention and please excuse me for not replying before

**Comment by rct** [comment] 2015-07-21 17:46
Take a look at my comment above.

There is a little bit of a process to get things going.

First you need to make sure you are receiving a signal, which usually means getting the right frequency after correcting for the PPM error.  and a reasonable detection threshold (-l) depending on how far away your station is from your receiver.

After that -a -t, can help record signals that can be picked apart.  -D will also help analyze the signal.

Also, since the code you referenced already decodes the protocol, some protocol documentation as well as code could be pulled out of that.

**Comment by maaw** [comment] 2015-07-21 17:58
Yes, I'll try the steps you described. 
I'm pretty close to the transmitter, but all I get is a column of 15 80s and 00s every forty-something seconds when scanning with -A argument. But I'm not sure what parameter should I change to get a more detailed dump. I tried increasing the detection threshold and the message seemed to fragment, but again I'm not very sure what's happening. 
I also have an AlectoV1 Weather Sensor next to the WH1081 transmitter and that message, of course, is decoded properly, so I can cross out signal / receiver issues.

**Comment by vestom** [comment] 2015-08-23 15:03
Hi,

Did you ever succeed in getting it to work? If you add some test files to https://github.com/merbanan/rtl_433_tests, I can try to help. I did the code for the Fine Offset WH2, and they might have something in common.

We are also very interested in test files for the AlectoV1, as they are currently missing. Even though it works now, we might have regressions without test files.

I do not believe it should be necessary to mess with the PPM offset. The detection actually works best, when the signal is offset from the tuner centre frequency, as the tuner may have a so called DC filter.

Just try to record some files with -a -t and maybe try with the (brand new) pulse analyzer function by using -A (big A).

/Tommy

**Comment by 9m2tpt** [comment] 2015-09-10 13:47
Anybody has any luck on this one? I've just come across rtl_433 and thinking of having my wh1080 decoded by rtl_433 rather than using the console.

**Comment by marianowadel** [comment] 2015-09-10 14:38
Hi, sorry for not replying before, I haven't had the time. I've managed to make it work with ookd's decoder (https://github.com/jimstudt/ook-decoder). You need only launch ookd, and then run wh1080. 
I'd like to get it to work with rtl_433, but I won't be able to give it a try again until october (Q3 end here at work).
Ideally, I'd like to replace fowsr's functionality (https://code.google.com/p/fowsr/), that pulls data via USB from the wh1080's console, with rtl_433 + a barometer. 
The reason is the console is very unstable, and hangs every 1 or 2 weeks. Plus the built in barometer started failing.
I promise I'll keep you guys updated.
Cheers

**Comment by maaw** [comment] 2015-09-10 14:39
Hi, sorry for not replying before, I haven't had the time. I've managed to make it work with ookd's decoder (https://github.com/jimstudt/ook-decoder). You need only launch ookd, and then run wh1080. 
I'd like to get it to work with rtl_433, but I won't be able to give it a try again until october (Q3 end here at work).
Ideally, I'd like to replace fowsr's functionality (https://code.google.com/p/fowsr/), that pulls data via USB from the wh1080's console, with rtl_433 + a barometer. 
The reason is the console is very unstable, and hangs every 1 or 2 weeks. Plus the built in barometer started failing.
I promise I'll keep you guys updated.
Cheers

**Comment by merbanan** [comment] 2015-09-10 17:43
@9m2tpt and @maaw. You can start with sending recordings of the signal to the rtl_433_tests repository. Then others can aid in development also.

**Comment by 9m2tpt** [comment] 2015-09-11 00:07
I have done the recording but having hard time to find a way to upload them
to the repository. Will find a way to upload.

**Comment by 9m2tpt** [comment] 2015-09-21 07:53
Hi @merbanan , since I've no idea how to upload them into the repository, the gdata files can be found in my shared google drive.

https://drive.google.com/folderview?id=0B1aqySKViHWSVENtNldTUWVmZ1E&usp=sharing

there are four files there, let me know if you need extra.

**Comment by ovrheat** [comment] 2016-02-12 01:10
Good news: WH1080 is now supported on rtl_433 (tested on its 868.3 Mhz version, it **_should_** work for other versions too: just adjust -f  (frequency) parameter, and use -l 0 as level parameter (auto)).
For my 868.3 version the working command line is 'rtl_433 -f 868250000 -l 0' .
Time signal decoding is also full working.
I need some feedback, so let me know.

**Comment by maaw** [comment] 2016-02-12 12:02
ovrheat, that's awesome. I've broken my raspbian microsd card so I'm not
able to test it right now, but i'll get it fixed asap in order to try this.
Thank you for your work, and sorry for not being so helpful.
I'll let you know when I test it.
Cheers!

2016-02-11 22:10 GMT-03:00 ovrheat <notifications@github.com>:

**Comment by 9m2tpt** [comment] 2016-02-12 13:39
Just tested with my WH1080 using the standard frequency at 433.920MHz (got mine few years ago from Maplin) and it works great. The only problem probably the frequency drifting on my RTL_SDR, I need to take a look into it. Thanks @ovrheat for the good job.

**Closed** 2016-02-12 13:46 UTC
