### ISSUE TITLE
CSV output columns need to follow the conversion option

### ISSUE THREAD

**Issue by pclov3r** [merbanan/rtl_433#1137] opened 2019-08-29 06:16 UTC
So I am using rtl_433 with customary units and it appears in the CSV file it still wants to attempt to log the temperature in C instead of F. As a result this column remains blank. 

This intended behavior or a bug?

**Comment by zuckschwerdt** [comment] 2019-08-29 06:22
The conversion should work, data is converted before looking at the output. The column header will be wrong though (untranslated). The problem is that column keys are fixed and don't go through a conversion step.

**Comment by pclov3r** [comment] 2019-08-29 06:27
Thanks for the quick acknowledgement of the issue!

**Comment by zuckschwerdt** [comment] 2019-08-29 07:10
As a quick fix, enable one protocol that has native customary output.
E.g. `-R 19 -R 52` for Nexus with the `temperature_F` key from Bresser.

**Comment by zuckschwerdt** [comment] 2019-08-29 11:40
Fixed with f1b3d18.

**Closed by zuckschwerdt** 2019-08-29 11:40 UTC
Labels: todo
