### ISSUE TITLE
Decoding Flowis water meter

### ISSUE THREAD

**Issue by vierundvierzig** [merbanan/rtl_433#2317] opened 2023-01-16 07:41 UTC
[Originally topic was started on wmbusmeters project.](https://github.com/weetmuts/wmbusmeters/issues/676)

Now I am in place that it should be decode from the beginning using rtl_433. I can grab some sample files from today:
[sample_files.zip](https://github.com/merbanan/rtl_433/files/10423493/sample_files.zip)

I tried to analyze them but it says nothing to me...

Any help will be greatly appreciated!

**Comment by zuckschwerdt** [comment] 2023-01-16 09:05
It's 100 kbps FSK, so could be M-Bus Mode C / T (or just similar).
This gets the data: `rtl_433 -R 0 -X 'n=name,m=FSK_PCM,s=10,l=10,r=500'`
```
g010_868M_1000k.cu8: {233}8008aa22d391d3911201f60f000f81c3f0607cef000000470000e77ff78
g011_868M_1000k.cu8: {162}c000555561c8e9c88981df27a8870000000000000 {18}fcb20
g012_868M_1000k.cu8: {234}800002aad391d3911201be4f410e81da74607cff000000450000e71f8dc
g013_868M_1000k.cu8: {161}8000828bc381c3911303be0f010e0000000000000 {17}fcb20
g014_868M_1000k.cu8: {233}802aaaaad381f3811201f64f410f81f074607cff000000450000a7977d8
g015_868M_1000k.cu8: {161}80003aa8c391d3911303f60f510e0000000000000
```

**Comment by merbanan** [comment] 2023-01-16 20:23
The signals look ok but you need the proper demod and longer reset value, so rtl_433 -f 868M -s 1000k  -X 'n=name,m=FSK_PCM,s=10,l=10,r=5000'

```
 g010_868M_1000k.cu8: {229}aaaaaaad391d3911[201]b64f510e[81c374605cef000000450000a5[5ff7]]0
 g012_868M_1000k.cu8: {228}aaaaaaad391d3911[201]b64f510e[81da74605cef000000450000a5[1b8d]]
 g014_868M_1000k.cu8: {228}aaaaaaad391d3911[201]b64f510e[81f074605cef000000450000a5[977d]]
 g011_868M_1000k.cu8: {236}aaaaaaad391d3911[302]b64f510e000000000000000000000000000[0fcb2]
 g013_868M_1000k.cu8: {235}aaaaaaad391d3911[302]b64f510e000000000000000000000000000[1f964]
 g015_868M_1000k.cu8: {237}aaaaaaad391d3911[302]b64f510e000000000000000000000000000[0fcb2]0

```
So the signal consist of a preamble and then some header. From the signals we here see 2 different packets 201 and 302. Then some more data and then some payload depending on the packet and then at the end there are 4 values that might be a CRC.

**Comment by merbanan** [comment] 2023-01-16 20:35
Now we need a large set of received messages (1000 would be nice to start with). Then we need to try to match it with possible data, serial number and the meter value. We need to figure out the shift also. aad391 has a 25% chance of being correct.

If the collection part is boring then build a webcam rig that grabs a photo whenever there is a new transmission.

**Comment by merbanan** [comment] 2023-01-16 21:24
And for the record the long sequence of zeroes in one type of message de-syncs the bitstream. So this is not wmbus this is some proprietary scheme. The existence of desyncs indicates that it is not that well designed and most likely only one user of the protocol.

Anyway we should be able to fix the bit stream if we detect a long period of zeroes. It looks like the message after the preamble is 200 bits long.

**Comment by zuckschwerdt** [comment] 2023-01-16 21:30
The `d391 d391` is a known sync word (rojaflex.c, marlec_solar.c, archos_tbh.c, maverick_xr30.c).
16-bit chunking from there on looks promising, though the first three are a byte shorter.
The g013 is broken, all other check out with CRC-16 poly 0x8005 init 0xffff. (*I edited your code grouping*)

**Comment by merbanan** [comment] 2023-01-16 21:31
./reveng -s -w 16 d391d3911201b64f510e81c374605cef000000450000a55ff7 d391d3911201b64f510e81da74605cef000000450000a51b8d d391d3911201b64f510e81f074605cef000000450000a5977d 
width=16  poly=0x8005  init=0x1818  refin=false  refout=false  xorout=0x0000  check=0xabbd  residue=0x0000  name=(none)

**Comment by merbanan** [comment] 2023-01-16 21:33
So poly poly=0x8005 looks good. And we can then fix the bit stream if it gets desynced.

**Comment by zuckschwerdt** [comment] 2023-01-16 21:33
Start after the sync for a nice init of 0xffff :)

**Comment by merbanan** [comment] 2023-01-16 21:34
Yeah, init and check looked off.

**Comment by zuckschwerdt** [comment] 2023-01-16 21:37
g013 with one 0-bit inserted is `1302b64f510e000000000000000000000000000fcb2` and checks out ;)

**Comment by merbanan** [comment] 2023-01-16 21:38
> g013 with one 0-bit inserted is `1302b64f510e000000000000000000000000000fcb2` and checks out ;)

Desync but you now proved it can be handled.

**Comment by merbanan** [comment] 2023-01-16 21:39
So @vierundvierzig, we now have a quite good understanding of the structure of the messages. You now need to vary one parameter and observe the change in message. From the picture we see 2 meters, that should help out to identify the meter id.

**Comment by vierundvierzig** [comment] 2023-01-16 22:42
Wow, I am impressed of you guys :)
I will do my best, but meters send signals when I am at work... As soon as I figure something out I let you know.

PS. They also send some additional information like:
- value at the end of previous month (in liters)
- value since 1st day of the month till today (in liters)
- warning about magnet field
- warning about reverse flow

**Comment by zuckschwerdt** [comment] 2023-01-17 09:22
The first byte (after the sync) is the length, so 12 (18) and 13 (19).
This is very similar to Marlec Solar iBoost+ and Archos-TBH (but different bitrate), likely because it's based on a TI CC1100 I'd guess.

We can implement a decoder, but you will need to watch the payload (type 1 and type 2 above) and make deductions.
If the fields after the type code are addresses/IDs, the this is the info you are looking for: `81f074605cef000000450000a5` -- the consumption value is that.

**Comment by vierundvierzig** [comment] 2023-01-17 09:29
I took one meter (id: 240234918) to work but I can see on waterfall very strong, stable signal on 868.01MHz... Anyway, I change the readings on it to 00000.251 and recorded some sample:
[sample_2402349718_00000251.zip](https://github.com/merbanan/rtl_433/files/10433414/sample_2402349718_00000251.zip)
I hope it will be ok. If yes, I can do some more readings

**Comment by zuckschwerdt** [comment] 2023-01-17 13:48
Yes, the codes are good:
```
aaaaaaa d391 d391 1201 a6b1 510e 81f996625cf1000000110000a5 7168
aaaaaaa d391 d391 1302 a6b1 510e 1c00000000000000000000000201 5ff4
aaaaaaa d391 d391 1201 a6b1 510e 811e97625cf1000000110000a5 0a87
aaaaaaa d391 d391 1302 a6b1 510e 1c00000000000000000000000201 5ff4
aaaaaaa d391 d391 1201 a6b1 510e 814497625cf1000000110000a5 1191
aaaaaaa d391 d391 1302 a6b1 510e 1c00000000000000000000000201 5ff9
```
Now we need a series of samples or codes with sample changes (counting up).
Use e.g. `rtl_433 -f 868M -s 1000k -X 'n=name,m=FSK_PCM,s=10,l=10,r=5000'` to get codes and paste a list like:
```
{229}555555569c8e9c88900d358a88740fccb312e7880000008800052b8b40 [00000.251]
```

**Comment by vierundvierzig** [comment] 2023-01-17 14:37
```{230}555555569c8e9c88900d358a88740f373312e7a00000008800052a40d4 [00000.254]
{237}555555569c8e9c889815358a8870f80000000000000000000000080567f8 [00000.254]
{229}555555569c8e9c88900d358a887408273b12e7a00000008800052f93b0
{237}555555569c8e9c889815358a8870f80000000000000000000000100acff8 [00000.254]
{230}555555569c8e9c88900d358a887408f73b12e7a00000008800052bb470 [00000.254]


{230}555555569c8e9c88900d358a88740d6f3b12e7c80000008800052e8f4c  [00000.259]
{236}555555569c8e9c889815358a887120000000000000000000000010017c7 [00000.259]
{230}555555569c8e9c88900d358a88740e5f3b12e7c80000008800052e07c0 [00000.259]
{236}555555569c8e9c889815358a887120000000000000000000000010017c7 [00000.259]
{230}555555569c8e9c88900d358a88740f2f3b12e7c80000008800052e6fa8 [00000.259]
{236}555555569c8e9c889815358a887120000000000000000000000010017c7 [00000.259]

 
{230}555555569c8e9c88900d358a887409cf4312e7f80000008800052e47c0 [00000.265]
{238}555555569c8e9c889815358a88715000000000000000000000000804ce54 [00000.265]
{229}555555569c8e9c88900d358a88740abf4312e7f80000008800052ad0b0 [00000.265]
{236}555555569c8e9c889815358a887150000000000000000000000010099ca [00000.265]
{230}555555569c8e9c88900d358a88740b8f4312e7f80000008800052ea724 [00000.265]
{237}555555569c8e9c889815358a887150000000000000000000000010099ca8 [00000.265]

 
{229}555555569c8e9c88900d358a8874081f4b12e0400800008800052d2d98 [00000.274]
{236}555555569c8e9c889815358a887198000000000000000000000010000d0 [00000.274]
{229}555555569c8e9c88900d358a887408ef4b12e0400800008800052d05b0 [00000.274]
{236}555555569c8e9c889815358a887198000000000000000000000010000d0 [00000.274]
{230}555555569c8e9c88900d358a887409bf4b12e040080000880005296230 [00000.274]
{237}555555569c8e9c889815358a887198000000000000000000000010000d08 [00000.274]

 
{229}555555569c8e9c88900d358a88740d875312e0700800008800052c6970 [00000.280]
{236}555555569c8e9c889815358a8871c800000000000000000000001000ada [00000.280]
{229}555555569c8e9c88900d358a88740eb75312e0700800008800052ce1f8 [00000.280]
{239}555555569c8e9c889815358a8871c80000000000000000000000080056d2 [00000.280]
{231}555555569c8e9c88900d358a88740fbf5312e0700800008800052a9d92 [00000.280]
{237}555555569c8e9c889815358a8871c800000000000000000000001000ada0 [00000.280]```

Now it looks different....

**Comment by zuckschwerdt** [comment] 2023-01-17 14:46
Very good. Drop in [a BitBench like this](https://triq.net/bitbench#c=%7B230%7D555555569c8e9c88900d358a88740f373312e7a00000008800052a40d4%20%5B00000.254%5D&c=%7B229%7D555555569c8e9c88900d358a887408273b12e7a00000008800052f93b0%20%5B00000.254%5D&c=%7B230%7D555555569c8e9c88900d358a887408f73b12e7a00000008800052bb470%20%5B00000.254%5D&c=%7B230%7D555555569c8e9c88900d358a88740d6f3b12e7c80000008800052e8f4c%20%20%5B00000.259%5D&c=%7B230%7D555555569c8e9c88900d358a88740e5f3b12e7c80000008800052e07c0%20%5B00000.259%5D&c=%7B230%7D555555569c8e9c88900d358a88740f2f3b12e7c80000008800052e6fa8%20%5B00000.259%5D&c=%7B230%7D555555569c8e9c88900d358a887409cf4312e7f80000008800052e47c0%20%5B00000.265%5D&c=%7B229%7D555555569c8e9c88900d358a88740abf4312e7f80000008800052ad0b0%20%5B00000.265%5D&c=%7B230%7D555555569c8e9c88900d358a88740b8f4312e7f80000008800052ea724%20%5B00000.265%5D&c=%7B229%7D555555569c8e9c88900d358a8874081f4b12e0400800008800052d2d98%20%5B00000.274%5D&c=%7B229%7D555555569c8e9c88900d358a887408ef4b12e0400800008800052d05b0%20%5B00000.274%5D&c=%7B230%7D555555569c8e9c88900d358a887409bf4b12e040080000880005296230%20%5B00000.274%5D&c=%7B229%7D555555569c8e9c88900d358a88740d875312e0700800008800052c6970%20%5B00000.280%5D&c=%7B229%7D555555569c8e9c88900d358a88740eb75312e0700800008800052ce1f8%20%5B00000.280%5D&c=%7B231%7D555555569c8e9c88900d358a88740fbf5312e0700800008800052a9d92%20%5B00000.280%5D&c=&c=%7B237%7D555555569c8e9c889815358a8870f80000000000000000000000080567f8%20%5B00000.254%5D&c=%7B237%7D555555569c8e9c889815358a8870f80000000000000000000000100acff8%20%5B00000.254%5D&c=%7B236%7D555555569c8e9c889815358a887120000000000000000000000010017c7%20%5B00000.259%5D&c=%7B236%7D555555569c8e9c889815358a887120000000000000000000000010017c7%20%5B00000.259%5D&c=%7B236%7D555555569c8e9c889815358a887120000000000000000000000010017c7%20%5B00000.259%5D&c=%7B238%7D555555569c8e9c889815358a88715000000000000000000000000804ce54%20%5B00000.265%5D&c=%7B236%7D555555569c8e9c889815358a887150000000000000000000000010099ca%20%5B00000.265%5D&c=%7B237%7D555555569c8e9c889815358a887150000000000000000000000010099ca8%20%5B00000.265%5D&c=%7B236%7D555555569c8e9c889815358a887198000000000000000000000010000d0%20%5B00000.274%5D&c=%7B236%7D555555569c8e9c889815358a887198000000000000000000000010000d0%20%5B00000.274%5D&c=%7B237%7D555555569c8e9c889815358a887198000000000000000000000010000d08%20%5B00000.274%5D&c=%7B236%7D555555569c8e9c889815358a8871c800000000000000000000001000ada%20%5B00000.280%5D&c=%7B239%7D555555569c8e9c889815358a8871c80000000000000000000000080056d2%20%5B00000.280%5D&c=%7B237%7D555555569c8e9c889815358a8871c800000000000000000000001000ada0%20%5B00000.280%5D&f=8h8h%20&a=Preamble&m=d391d391&cw=4) (sorted by msg type here) and we do see some counters!

**Comment by merbanan** [comment] 2023-01-17 14:49
```
{230}555555569c8e9c88900d358a88740[d]6f3b12e7c80000008800052e8f4c  [00000.259]
{230}555555569c8e9c88900d358a88740[e]5f3b12e7c80000008800052e07c0 [00000.259]
{230}555555569c8e9c88900d358a88740[f]2f3b12e7c80000008800052e6fa8 [00000.259]

{230}555555569c8e9c88900d358a88740[9]cf4312e7f80000008800052e47c0 [00000.265]
{229}555555569c8e9c88900d358a88740[a]bf4312e7f80000008800052ad0b0 [00000.265]
{230}555555569c8e9c88900d358a88740[b]8f4312e7f80000008800052ea724 [00000.265]

{229}555555569c8e9c88900d358a88740[8]1f4b12e0400800008800052d2d98 [00000.274]
{229}555555569c8e9c88900d358a88740[8]ef4b12e0400800008800052d05b0 [00000.274]
{230}555555569c8e9c88900d358a88740[9]bf4b12e040080000880005296230 [00000.274]

{229}555555569c8e9c88900d358a88740[8]d875312e0700800008800052c6970 [00000.280]
{229}555555569c8e9c88900d358a88740[e]b75312e0700800008800052ce1f8 [00000.280]
{231}555555569c8e9c88900d358a88740[f]bf5312e0700800008800052a9d92 [00000.280]
```

This position counts up in the package group it is in.

**Comment by zuckschwerdt** [comment] 2023-01-17 14:51
That would be CTR for `LEN:8d MSG:8h ID?8h8h 8h8h VAL?16d CTR?8h 8h8h 8h 8h8h 8h8h 8h8h 8h CRC:8h8h IGNORE:8h` format in the BitBench above, right?

**Comment by zuckschwerdt** [comment] 2023-01-17 14:55
ah, found it: "AMOUNT" with `LEN:8d MSG:8h ID?8h8h 8h8h VAL?16h CTR?8h 8h8h AMOUNT:<32d 32h CRC:8h8h IGNORE:8h`

**Comment by merbanan** [comment] 2023-01-17 16:05
The ID is correct also: 240234918 -> E51B1A6. It looks like this in the bitbuffer: ID?a6b1 510e. So we just reverse the value and we are done: 0e51b1a6.

**Comment by zuckschwerdt** [comment] 2023-01-17 17:21
Ok little endian then ;) `LEN:8d MSG:8h ID:<32d ?8h CTR?<32h AMOUNT:<32d 32h CRC:8h8h IGNORE:8h`
And maybe the "CTR" field also. We need to see a rollover, so more codes please ;)
Codes 5c62e6e6 going to 5c62eaf7 need to go to 5c62ffff, and then 5c630000 if the guess is correct (is it maybe a time value?).

**Comment by merbanan** [comment] 2023-01-17 19:25
And just as an observation the amount value is 10 less then the observed value.

AMOUNT:0000000255 [00000.265]
AMOUNT:0000000264 [00000.274]
AMOUNT:0000000270 [00000.280]

**Comment by vierundvierzig** [comment] 2023-01-17 23:20
> Ok little endian then ;) `LEN:8d MSG:8h ID:<32d ?8h CTR?<32h AMOUNT:<32d 32h CRC:8h8h IGNORE:8h` And maybe the "CTR" field also. We need to see a rollover, so more codes please ;) 

CTR?<32d looks like some kind of timestamp. You can spot 30 seconds between some messages. But then "1549985510" is timestamp for Tue Feb 12 2019 15:31:50 GMT+0000 and it doesn't make sense

**Comment by merbanan** [comment] 2023-01-17 23:32
If it is a CC1100 transceiver then you could send a command to the device to update the time in a device. To me the timestamp matches to well for it to not be that. That it is the wrong date doesnt really matter. The date is known by the consumer and the message timestamp delta is of interest. We do get a timestamp from rtl_433 so it is kind of redundant but identifying more fields is always good.

**Comment by merbanan** [comment] 2023-01-17 23:37
Anyway this should be enough for a decoder. The decoder should dump the raw buffers for msg types other then 1 and 2.  There where a few more possible packets listed in the issue thread.

```
value at the end of previous month (in liters)
value since 1st day of the month till today (in liters)
warning about magnet field
warning about reverse flow
```

**Comment by vierundvierzig** [comment] 2023-01-18 09:09
So what is next step? Are you going to implement new decoder or I should do some work (I have no idea what)?

**Comment by merbanan** [comment] 2023-01-18 13:42
Short term someone should write a decoder. Long term you need to record lots of messages so that we can try to figure out more parameters.

**Comment by vierundvierzig** [comment] 2023-01-18 14:22
Ok, I will do my best to record messages. And I will read information via dedicated device for this meters, so we will know what values we are looking for.

PS. I have small radio device for 868MHz, TTGO LoRa OLED. I'm trying to receive those packets via RadioLib library, but no success. Do you know that library? Could you point me what I should set? My settings for now:

```
  int state = radio.beginFSK();
  state = radio.setFrequency(868.0);
  state = radio.setBitRate(1000);
  state = radio.setFrequencyDeviation(150.0);
  state = radio.setRxBandwidth(250.0);
  state = radio.disableAddressFiltering();
  state = radio.setPreambleLength(4);
  uint8_t syncWord[] = {0xd3, 0x91, 0xd3, 0x91};
  state = radio.setSyncWord(syncWord, 4);
```

**Comment by merbanan** [comment] 2023-01-18 14:27
Are you sure the chip can handle FSK modulation? The settings look fairly sane to me.

**Comment by zuckschwerdt** [comment] 2023-01-18 14:30
> PS. I have small radio device for 868MHz, TTGO LoRa OLED.

A LoRa radio won't be compatible, right? Is the `setBitRate(1000)` 1000 bps (typical for LoRa)? We'd need 100 kbps…

**Comment by matthias-bs** [comment] 2023-01-18 14:49
The chip is an Semtech SX1276 or HopeRF95W (or compatible) which supports 100 kbps in FSK mode. Receiving data from Bresser Weather Stations based on RadioLib seems to work: https://github.com/matthias-bs/BresserWeatherSensorReceiver

**Comment by vierundvierzig** [comment] 2023-01-18 14:50
Yes, I'm sure the chip can handle FSK modulation, I use it for Open Glider Network which also works on FSK. From specification of SX1276: FSK, GFSK, MSK, GMSK, LoRa and OOK modulation.

From RadioLib docs:
setBitRate()
Sets FSK bit rate. Allowed values range from 1.2 to 300 kbps. Only available in FSK mode.

**Comment by matthias-bs** [comment] 2023-01-18 14:56
If I remember correctly, one important step was to disable CRC filtering:
        state = radio.setCrcFiltering(false);

In general (and especially for debugging) it is recommended to check the return value (`state`) after each configuration step to see if the settings were valid.

**Comment by merbanan** [comment] 2023-01-18 14:59
Ok, try to create a transmitter with about the same parameters as the Flowis meters. Then you can use rtl_433 to see if the signal looks the same on the receiving end.

**Comment by vierundvierzig** [comment] 2023-01-18 15:04
state = radio.setCrcFiltering(false);

Perfect shot! Thank you very much! I have still 5 minutes of TX :)

**Comment by vierundvierzig** [comment] 2023-01-22 08:40
Hi, a couple of days decoding and I have new ideas. 
First of all, packet length is different when meter recorded some kind of alarms. 
Second, amount represents <24d, not <32d.  Next 8d shows Alarm. When there is reverse flow it shows "032", when reverse flow and magnetic field: "160". Next byte is amount in liters of reverse flow.
Bytes between ID and Amount shows probably time and something else. Meters has for sure correct date and time. Using ' 8d <16d 8d 8d' for this part, I spotted on midnight that middle part (<16d 8d) counts something like seconds and days. Or it just look like...
For now, [this is my new BitBench](https://triq.net/bitbench#c=%7B248%7D2aaaad391d3911501a6b1510e818b746b5c6c0100200c0000a501000171945&c=%7B248%7D2aaaad391d3911501a6b1510e81a1746b5c6c0100200c0000a50100015b687&c=%7B245%7D2aaaad391d3911501a6b1510e81b8746b5c6c0100200c0000a5010001423e0&c=%7B248%7D2aaaad391d3911501a6b1510e81d2746b5c6c0100200c0000a50100012942f&c=%7B247%7D2aaaad391d3911501a6b1510e81e9746b5c6c0100200c0000a501000112d8e&c=%7B249%7D2aaaad391d3911501a6b1510e8103756b5c6c0100200c0000a50100017ba670&c=%7B248%7D2aaaad391d3911501a6b1510e811a756b5c6c0100200c0000a501000162f06&c=%7B245%7D2aaaad391d3911501a6b1510e8130756b5c6c0100200c0000a5010001480c8&c=%7B247%7D2aaaad391d3911501a6b1510e814c756b5c6c0100200c0000a501000135040&c=%7B245%7D2aaaad391d3911501a6b1510e818a766b5c6f0100a00c0000a5010003ce6f0&c=&c=%7B247%7D2aaaad391d3911501a6b1510e812e7e6b5c7c0100a00e0000a501000308594&c=MIDNIGHT&c=%7B248%7D2aaaad391d3911501a6b1510e81a7006c5c7c0100a00e0000a501000382974&c=%7B245%7D2aaaad391d3911501a6b1510e81f5016c5c7c0100a00e0000a501000350790&c=%7B246%7D2aaaad391d3911501a6b1510e818e046c5c7c0100a00e0000a50100032f660&c=%7B249%7D2aaaad391d3911501a6b1510e8101086c5c7c0100a00e0000a5010003af48b0%20%5B2023-01-22%2000%3A32%3A03%5D&c=%7B245%7D2aaaad391d3911501a6b1510e8184096c5c7c0100a00e0000a5010003a8540&c=%7B248%7D2aaaad391d3911501a6b1510e819c096c5c7c0100a00e0000a5010003b0045%20%5B2023-01-22%2000%3A38%3A30%5D&c=%7B246%7D2aaaad391d3911501a6b1510e81b3096c5c7c0100a00e0000a50100039fe60%20%5B2023-01-22%2000%3A38%3A53%5D&c=%7B249%7D2aaaad391d3911501a6b1510e81da0c6c5c7c0100a00e0000a5010003f29558%20%5B2023-01-22%2000%3A51%3A28%5D&c=%7B249%7D2aaaad391d3911501a6b1510e8120106c5c7c0100a00e0000a5010003969690%20%5B2023-01-22%2001%3A00%3A34%5D&c=&c=%7B249%7D2aaaad391d3911501a6b1510e8125936c5c7c0100a00e0000a5010003900870%20%5B2023-01-22%2009%3A12%3A40%5D&c=%7B249%7D2aaaad391d3911501a6b1510e8140956c5c7c0100a00e0000a5010003f25030%20%5B2023-01-22%2009%3A21%3A03%5D&f=LEN%3A8d%20___%20MSG%3A%208d___%20%20ID%3A%20%3C32d%20___%20%20TIME%3A%20%208d%20%3C16d%208d%208d___%20%20%20AMOUNT%3A%20%3C24d%20___%20ALARM%3A%208d%20AMOUNT_BACK_FLOW%3A%208d%20%20%3F%3F%3F%3F%208d%208d%208d%208d%208d%208d%20%20%20%20%20%20%20%20%20%20%3C24x&a=Preamble&m=d391d391&cl=1&cw=2)

**Comment by StKob** [comment] 2023-01-25 23:10
Are times that you written besides recording times of message being sent? That "<16d" is quite close to seconds from midnight at the beginning. For one at 00:32:03 I'm getting like 00:34:09 but for 09:21:03 its already 10:36:48. But it feels too close for it to be coincidence.

**Comment by vierundvierzig** [comment] 2023-01-27 12:32
Inspecting all data collected till today it seems to be a correct findings... And it should be also a year, hour, minute and seconds somewhere ;)

If you use "8d <32d" for this part it looks like timestamps and counts a seconds between readings perfectly correct.

**Comment by vierundvierzig** [comment] 2023-01-27 19:25
Solved :) I don't know how to write it on BitBench but this is my idea, i.e:

{249}2aaaad391d3911501a6b1510e81**25936c5c**7c0100a00e0000a5010003900870 [2023-01-22 09:12:40]
(* Note that it is a time of receiving by rtl_433)

Let's take this part: 25 93 6c 5c
In binary system: 00100101  10010011  01101100  01011100
Reverse and join: 01011100011011001001001100100101
And split again: 010111 0001 10110 01001 001100 100101
010111:  23
0001:  1
10110:  22
01001:  9
001100: 12
100101: 37

**Comment by StKob** [comment] 2023-01-28 13:42
Reverse and join is done by "<32b" but no idea how to split it again and read as decimal.

**Comment by StKob** [comment] 2023-02-01 15:53
I've got a bit of recording from time where 2 units got mounted in my house. Although its from rtl-sdr from crappy antenna and whole small town is getting equipped with those. 
[recording.txt](https://github.com/merbanan/rtl_433/files/10558881/recording.txt)

**Comment by merbanan** [comment] 2023-02-01 16:03
I'll see if I am able to get back to coding this evening.

**Comment by vierundvierzig** [comment] 2023-02-01 17:26
CRC is very important. I had situation that a small error gave good result for date, time and reading but changed one number in ID. And readings was assigned to wrong address...

**Comment by merbanan** [comment] 2023-02-01 23:07
https://github.com/merbanan/rtl_433/pull/2357

**Comment by merbanan** [comment] 2023-02-01 23:08
I'll add the date stuff later. Can I have some more signals ?

**Comment by StKob** [comment] 2023-02-02 08:23
I can record few days but there might be a lot garbage in it.

**Comment by StKob** [comment] 2023-02-03 18:44
[record 03.02.2023.txt](https://github.com/merbanan/rtl_433/files/10581817/record.03.02.2023.txt)

**Comment by merbanan** [comment] 2023-02-03 18:48
Use -S unknown.

**Comment by StKob** [comment] 2023-02-03 18:50
"rtl_433 -f 868M -s 1000k -X 'n=name,m=FSK_PCM,s=10,l=10,r=5000' -S unknown"   ?

**Comment by zuckschwerdt** [comment] 2023-02-03 19:08
In that case it needs to be `known` because you added a decoder (`-X`). So:
`rtl_433 -f 868M -s 1000k -R 0 -X 'n=name,m=FSK_PCM,s=10,l=10,r=5000' -S known`

**Comment by StKob** [comment] 2023-02-03 19:10
I used for a parameters what was in this issue higher up. Ok, so that would be good?

**Comment by merbanan** [comment] 2023-02-03 23:49
Timestamp decoding added to https://github.com/merbanan/rtl_433/pull/2357.

**Comment by merbanan** [comment] 2023-02-04 19:40
A decoder for this device has now been merged. Reopen if you figure out more parameters.

**Closed by merbanan** 2023-02-04 19:40 UTC

**Comment by StKob** [comment] 2023-02-06 08:39
I compiled it using VS2019. Starting with "rtl_433.exe -f 868M -s 1000k -R 237 -S known" Alarms number is increasing constantly. Am I using this right? Error while compiling?  

[rtl_433_1.zip](https://github.com/merbanan/rtl_433/files/10661113/rtl_433_1.zip)
[rtl_433_2.zip](https://github.com/merbanan/rtl_433/files/10661115/rtl_433_2.zip)
[rtl_433_3.zip](https://github.com/merbanan/rtl_433/files/10661117/rtl_433_3.zip)
[rtl_433_4.zip](https://github.com/merbanan/rtl_433/files/10661120/rtl_433_4.zip)

**Comment by StKob** [comment] 2023-02-07 11:40
`             "alarm",         "Alarm",     DATA_INT,    b[11],
             "backflow",      "Backflow",  DATA_INT,    b[12],`

Shouldn't this be b[14] and b[15] ?

**Comment by zuckschwerdt** [comment] 2023-02-07 11:57
At least the protocol description is off with `V 32b: Volume in m3` and `B C ... 15` does not sound right?

**Comment by StKob** [comment] 2023-02-12 13:16
@merbanan Would you take a look at this?

**Comment by merbanan** [comment] 2023-02-16 20:39
Should be fixed now.

**Comment by asquelt** [comment] 2023-03-17 11:11
some more data from active period (now).
my serial is: 240536163
(there may be others in the dump too, as entire residential had them installed this week)

(https://ze.psu.je/101jgF/my-radio-traffic-2.txt)[my-radio-traffic-2.txt]

**Comment by merbanan** [comment] 2023-03-18 20:41
Some decodes looks like flowis but you really need to single out the non working sensor for me to be able to do anything. Take a laptop and connect the rtl_sdr to it. Remove the antenna and then run rtl_433 -S unknown when next to the meter. You might need to adjust the gain value to be able to get a proper signal.

The idea is to only receive the non working transmissions and store them in a file for debugging purposes.

**Comment by asquelt** [comment] 2023-03-19 09:10
ok, I'll try to connect myself to the shaft tomorrow :) as they seem quiet during weekends.

**Comment by asquelt** [comment] 2023-03-27 12:58
@merbanan since it appears to be encrypted (probably using static key, given offline nature of official readers) is it viable to include a key in Flowis module or is it outside of the scope of this project?

**Comment by merbanan** [comment] 2023-03-27 19:10
If it is a static key then we can include it in the module. If it is configurable then we add it as an option.

**Comment by merbanan** [comment] 2023-03-27 19:29
Try playing with the gain (-g). Now we get what looks like flowis data but the signal clips and that causes 

![Screenshot from 2023-03-27 21-24-07](https://user-images.githubusercontent.com/124883/228045893-b56184ef-0810-4057-b9ed-21e88e3fe55a.png)

This is the decoded data:

codes     : {241}c000044061c8e9c009801001880744000000000000000000000000013c100
codes     : {282}0f8e2d391c38118016308560ec1f7c0e81ccc010000000000a10100809e00000074fc00
codes     : {235}0f8e0c391c3810302630a160e3601000000000000000000000000337202
codes     : {241}c044447569c8e1c089811245aa0744000000000000000000000000001e080
codes     : {281}03f8ed391c3901901e340760ec048c1e81ccc000000000000850500809e00000078f600
codes     : {233}0f8e0c381c3811302630a060e360000000000000000000000000166e400
codes     : {243}c045555d61c0e9c089801247880740000000000000000000000000004f110
codes     : {282}0faf8c391d3911900630e1e0ec197c1e05ccc010000000000870500809e000000f1f804
codes     : {160}1302630a560e3601000000000000000000000000
codes     : {234}0fafad391d3911302630a560e3601000000000000000000000000f37000

You can see the sync value in there for some values rows. And the data doesnt look encrypted to me.

**Comment by asquelt** [comment] 2023-03-28 11:40
I've checked every gain value between 10..500 and there are no 2405* meters appearing (only 2404* ones). Please if anyone manages to capture them, let me know in comments what hardware and settings you use. For now I consider my unit to be faulty.

**Comment by zuckschwerdt** [comment] 2023-03-28 11:58
> I've checked every gain value between 10..500

If you are using a RTL-SDR with R820T then possible gain values in rtl_433 are 0..50 (i.e. dB not deci-dB)

**Comment by merbanan** [comment] 2023-03-28 14:23
@asquelt it is possible that new meters have different payload that needs changes to the decoder. To me the signals looks similar but I have not manually decoded a message.

@zuckschwerdt maybe we can add some kind of metric in the output or filename to help people to set a proper gain? A clip detector would be nice to have.

**Comment by zuckschwerdt** [comment] 2023-03-28 15:03
We do know the RSSI in dBFS (it's the OOK envelope) and we show it with `-M level`. We would need to specify how many samples above what threshold to consider "clipping".
I see three cases here: (near) DC there will be multiple I/Q samples on nearly a straight line -- this is not clipping.
One of I/Q might hit near maximum and make a nearly a straight line -- this is clipping "badly" at -0 dBFS.
Since we basically just add I+Q we could get positive dB -- this is not necessarily clipping but beyond -0 dB.

For now though: the upcoming new Spectrogram (preview: https://triq.org/spectrogram-next/ ) indicates clipping (on the I/Q view and relative to the selected Gain) with color.

**Comment by vierundvierzig** [comment] 2023-04-09 09:45
> Let's take this part: 25 93 6c 5c
> In binary system: 00100101 10010011 01101100 01011100
> Reverse and join: 01011100011011001001001100100101
> And split again: 010111 0001 10110 01001 001100 100101
> 010111: 23
> 0001: 1
> 10110: 22
> 01001: 9
> 001100: 12
> 100101: 37

A small change to this. I think first figure is for summer time. 0 means winter, 1 means summer. For now it reads 110111 which is 55 and it is obviously wrong year. It should be 1 for summer and 10111 for 23 (year).

**Comment by StKob** [comment] 2023-04-09 09:49
EU is using DST. Time was changed last Sunday of March.

**Comment by asquelt** [comment] 2023-05-12 13:12
i can confirm this error. my Flowis readouts contain wrong date too.

```
rtl_433/rtl443/devices/1/Flowis/240431631/device_time 2055-05-12T15:08:33
rtl_433/rtl443/devices/1/Flowis/240428416/device_time 2055-05-08T15:54:52
rtl_433/rtl443/devices/1/Flowis/240421671/device_time 2055-05-08T13:09:08
rtl_433/rtl443/devices/1/Flowis/240421668/device_time 2055-05-12T15:04:01
rtl_433/rtl443/devices/1/Flowis/240431556/device_time 2055-05-12T15:03:55
rtl_433/rtl443/devices/1/Flowis/240431622/device_time 2055-05-12T15:02:39
rtl_433/rtl443/devices/1/Flowis/240427832/device_time 2055-05-12T15:02:12
rtl_433/rtl443/devices/1/Flowis/240421673/device_time 2055-05-12T15:02:45
rtl_433/rtl443/devices/1/Flowis/240431841/device_time 2055-05-12T15:03:43
rtl_433/rtl443/devices/1/Flowis/240508787/device_time 2055-04-25T13:54:00
rtl_433/rtl443/devices/1/Flowis/240538301/device_time 2055-04-06T08:54:52
rtl_433/rtl443/devices/1/Flowis/240427834/device_time 2055-04-28T10:37:53
rtl_433/rtl443/devices/1/Flowis/240426533/device_time 2055-03-28T11:51:42
rtl_433/rtl443/devices/1/Flowis/240431851/device_time 2055-03-28T11:52:54
rtl_433/rtl443/devices/1/Flowis/240428430/device_time 2055-04-04T10:55:02
rtl_433/rtl443/devices/1/Flowis/240428425/device_time 2055-05-05T15:55:16
rtl_433/rtl443/devices/1/Flowis/240431589/device_time 2055-03-28T11:51:27
rtl_433/rtl443/devices/1/Flowis/240426584/device_time 2055-05-03T10:53:53
rtl_433/rtl443/devices/1/Flowis/240536163/device_time 2055-05-01T08:44:59
rtl_433/rtl443/devices/1/Flowis/240538249/device_time 2055-05-01T11:34:52
rtl_433/rtl443/devices/1/Flowis/240539499/device_time 2055-05-02T15:41:25
rtl_433/rtl443/devices/1/Flowis/240473634/device_time 2055-04-25T13:46:22
```

**Comment by grumar** [comment] 2023-08-04 09:53
> Solved :) I don't know how to write it on BitBench but this is my idea, i.e:
> 
> {249}2aaaad391d3911501a6b1510e81**25936c5c**7c0100a00e0000a5010003900870 [2023-01-22 09:12:40] (* Note that it is a time of receiving by rtl_433)
> 
> Let's take this part: 25 93 6c 5c In binary system: 00100101 10010011 01101100 01011100 Reverse and join: 01011100011011001001001100100101 And split again: 010111 0001 10110 01001 001100 100101 010111: 23 0001: 1 10110: 22 01001: 9 001100: 12 100101: 37

My apologies for contacting you here.
@vierundvierzig, did you manage to run this on lora32 device? It looks like I've stuck on the same issue as yours.

**Comment by asquelt** [comment] 2023-09-22 14:00
i got one more meter with id starting with 2406 and it also doesn't decode with this code (with any gain combination).
