### ISSUE TITLE
No InfluxDB output using option "-E quit"

### ISSUE THREAD

**Issue by krypton-x** [merbanan/rtl_433#2285] opened 2022-12-21 00:17 UTC
Hi

I have noticed combining InfluxDB output together with option "-E quit" causes the current version of rtl_433 to stop sending results to the database. Without this option it works perfectly. Using an old version (20.02) also solves the problem.

In working condition the following TCP packets are sent:

![working](https://user-images.githubusercontent.com/47252901/208786163-9caab826-4ad6-4bd0-a5c0-e667296fff5c.png)

After adding "-E quit" the connection to the database gets established and closed but the HTTP packets are missing:

![quit](https://user-images.githubusercontent.com/47252901/208787258-18a337da-fdc6-4e99-a0ef-5a51e667e073.png)

Thanks for any help.

rtl_433 -V
rtl_433 version 22.11-26-g616b5d5e branch master at 202212201349

command used:
rtl_433 -d :77771111153705700 -R 92 -F "influx://127.0.0.1:8086/write?db=influxtest" -M time:unix:utc -E quit

uname -a
Linux raspberrypi4 5.15.76-v7l+ *1597 SMP Fri Nov 4 12:14:58 GMT 2022 armv7l GNU/Linux

**Comment by zuckschwerdt** [comment] 2022-12-21 10:44
Sadly this is "by design" currently. On receiving a transmission the "-E quit" will end the event loop and open connections won't get a chance to finish. This will be addressed by #1978

**Closed by zuckschwerdt** 2022-12-21 10:44 UTC
