### ISSUE TITLE
Rosenborg 66796 - invalid temperature

### ISSUE THREAD

**Issue by eyJhb** [merbanan/rtl_433#955] opened 2019-01-13 13:24 UTC
I just bought the Rosenborg 66796 (listed [here](https://www.bilka.dk/elektronik/ure-og-vejrstationer/vejrstationer-og-termometre/rosenborg-traadloes-vejrstation-model-66796/p/100183695) - danish website), and it worked perfectly with this software, EXCEPT that the temperature was measured wrong.

It is detected as a `Fine Offset WH5 sensor`, and from that it gathers that it needs to offset the temperature reading by `temp -= 400`, which produces the invalid temperature.

https://github.com/merbanan/rtl_433/blob/d09827abe4d0065c5bb3a892936c1d315481a5ea/src/devices/fineoffset.c#L93-L96

Commenting out that line, fixes the problem..

I don't know if this is a "one off" issue, but it might be relevant to just remove that code, as it does not provide the original function anymore.

EDIT: I made a PR for this.

**Comment by zuckschwerdt** [comment] 2019-01-13 13:57
The problem is not the WH5 code but your device being detected as WH5. Please provide a captured sample.

**Comment by eyJhb** [comment] 2019-01-13 14:01
How would you like me to capture it? `-S all`?

**Comment by eyJhb** [comment] 2019-01-13 14:10
Attached the file as .log, feel free to rename it @zuckschwerdt 
[g007_433.92M_250k.log](https://github.com/merbanan/rtl_433/files/2753143/g007_433.92M_250k.log)

It functions perfectly, when it is NOT detected as a WH5. But just seems weird, that the magic bits are identical.

**Comment by zuckschwerdt** [comment] 2019-01-13 14:18
Perfect clean capture, thanks! I'll try to figure out how this variant fits with all the subtle differences.

**Comment by eyJhb** [comment] 2019-01-13 14:20
@zuckschwerdt perfect! You can hit me up on Freenode if you want to, and if I can help with anything :) - I am currently trying to figure out the `0x04` part of the protocol, as I would like to know if this is a battery thing!

**Comment by zuckschwerdt** [comment] 2019-01-13 14:36
Looks like your Rosenborg 66796 uses the exact same timing and bits as the (Imagintronix) WH5. (s.a. #239).
At a glance I don't see a way to reconcile that. Perhaps you can compare to https://github.com/merbanan/rtl_433_tests/tree/master/tests/imagintronix_wh5 and see if threre are any solid differences?

**Comment by zuckschwerdt** [comment] 2019-01-13 14:40
Ok, so the Rosenborg 66796 uses the same encoding as all the other WH2-type sensors (sounds plausible, might be just missing the first preamble bit.). And the exception for the WH5 (missing first bit -> unsigned, offset 40) breaks it.

**Comment by eyJhb** [comment] 2019-01-13 14:43
So the challenge right now, is to identify is as a separate type of sensor, instead of using the WH5 logic. Right?

So what can be done from here, more testing? - I have not worked that much with RF; and not in the form of comparing etc! But I would gladly learn, if you would tell me what to do :) (more or less what I need to do at least;programs etc.)

**Comment by zuckschwerdt** [comment] 2019-01-13 14:51
I'd say your sensor is the "normal" one and the WH5 is the "strange" device. If there is anything to distinguish both that would be great. But `rtl_433 -A` and `rtl_433 -R 0 -X 'n=raw,m=OOK_PWM,s=500,l=1500,r=1200'` seem to deliver the exact same kind of data when run on either samples :/
Perhaps you can spot something. Maybe also try the `sigrok-open.sh` script.

**Comment by eyJhb** [comment] 2019-01-13 15:06
I cannot even spot, how it decodes the output I am getting... Ohh, the joys of being new in the field.

```
root@67644ab293a6:/src/rtl_433/src# ./rtl_433 -r g007_433.92M_250k.log -X 'n=raw,m=OOK_PWM,s=500,l=1500,r=1200'
rtl_433 version unknown inputs file rtl_tcp RTL-SDR
Trying conf file at "rtl_433.conf"...
Trying conf file at "/root/.rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Registered 97 out of 120 device decoding protocols [ 1-4 8 11-12 15-21 23 25-26 29-36 38-60 62-64 67-71 73-100 102-103 108-116 119 ]
Test mode active. Reading samples from file: g007_433.92M_250k.log
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : @0.088432s
model     : raw          count     : 1             num_rows  : 1             rows      : 
len       : 47           data      : fe8370aa420c
codes     : {47}fe8370aa420c
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : @0.088432s
model     : Fine Offset WH5 sensor                 ID        : 27
Temperature: -8.5 C      Humidity  : 33 %          Integrity : CRC
```

I am guessing the `fe8370aa420c` contains all the information, including the ID, temp reading, humidity, etc. correct?

**Comment by eyJhb** [comment] 2019-01-13 15:18
Hmm, no I can't see anything either that differentiate them from each other.. Except that one thing...
Wondering if we can make some kind of check in the code, that could detect either of them..
But the only place where this is possible, is when the sensor reaches a negative temperature, as it will then read it as "+200"...

Else the only thing is, that the initial temperature is read as negative, but that cannot be used as a indicator either, as some people might place it in a -18 C place....

**Comment by zuckschwerdt** [comment] 2019-01-13 15:20
Yes, `-R 0` disables all decoders and `-X ...` adds a new flex decoder. The `codes` are all the bits found. It's really just 47 plain bits.
The Sigrok Pulseview can show the decoding in detail, see #800 for what you'd get.

Ah yes, a heuristic on plausible temperature values could work.

**Comment by zuckschwerdt** [comment] 2019-01-13 15:53
Too bad, yes. Using the top bit to decide would mean: The usual case works for all negative temperatures, the WH5 case looses the upper half of positive values (everything above raw 2047-400, i.e. 164.7 C would be seen as negative value).
Problem are the positive values. A value of raw 220 could be either 22.0 (normal case) or -18.0 (WH5) -- no way to decide that :/

**Comment by merbanan** [comment] 2019-01-13 15:57
rtl_433_tests/tests/imagintronix_wh5/gfile007.cu8 ->

Pulse width distribution:
 [ 0] count:   23,  width:  432 us [428;460]	( 108 S)
 [ 1] count:   24,  width: 1412 us [1404;1420]	( 353 S)


g007_433.92M_250k.log ->

Pulse width distribution:
 [ 0] count:   21,  width:  504 us [500;512]	( 126 S)
 [ 1] count:   26,  width: 1480 us [1476;1488]	( 370 S)


So with regards to the test samples it is possible to differentiate the Rosenborg 66796 and the tests samples at hand.

**Comment by merbanan** [comment] 2019-01-13 16:00
But this heuristics is weak. I think we need quirk parameter that can be set in the config.

**Comment by merbanan** [comment] 2019-01-13 16:02
It is obvious that the oem for the same design use different components on the sensor side and then fix it up in the receiver.

**Comment by eyJhb** [comment] 2019-01-13 16:05
@merbanan  sounds like a plan with the parameter in the config, I am guessing it is a bool which can specify which type is used? - Which would then be the default one?

**Comment by zuckschwerdt** [comment] 2019-01-13 16:09
We could add a new (default disabled) decoder and then you can select with e.g. `-R -78 -R 121` (i.e. disable the default, enable the quirk one).
I'd rather make the WH5 the special case. As Rosenborg 66796 fits with the common WH2 case. But disabling an old and established decoder will cause grief…

**Comment by eyJhb** [comment] 2019-01-13 16:18
@zuckschwerdt backwards compatibility is always nice!

Off topic question, as I have no clue how to contact you guys anywhere else. Can you recommend device which works with the library, that is cheap and has temperature/humidity sensor too? Preferably available in Europe.

**Comment by merbanan** [comment] 2019-01-13 16:47
@zuckschwerdt I now think we can differentiate between the devices. The Pulse period distribution between the different devices are the same:

imagintronix_wh5/gfile007.cu8
Pulse period distribution:
 [ 0] count:   23,  width: 1464 us [1460;1480]	( 366 S)
 [ 1] count:   23,  width: 2440 us [2432;2456]	( 610 S)
Gap width distribution:
 [ 0] count:   46,  width: 1028 us [1016;1036]	( 257 S)
Pulse width distribution:
 [ 0] count:   23,  width:  432 us [428;460]	( 108 S)
 [ 1] count:   24,  width: 1412 us [1404;1420]	( 353 S)

g007_433.92M_250k.log:
Pulse period distribution:
 [ 0] count:   21,  width: 1464 us [1460;1472]	( 366 S)
 [ 1] count:   25,  width: 2440 us [2436;2448]	( 610 S)
Gap width distribution:
 [ 0] count:   46,  width:  960 us [952;968]	( 240 S)
Pulse width distribution:
 [ 0] count:   21,  width:  504 us [500;512]	( 126 S)
 [ 1] count:   26,  width: 1480 us [1476;1488]	( 370 S)

but the pulse length differed. This means we can do a heuristic for < gap width limit and > pulse width limit for one device and then check the reverse for the other device. That looks reliable as the accumulated difference with the pulse and gap added is ca 130us (~8%). To me that is enough to say it is one or the other. The only problem is that I am not sure the demodulator passes this value to the decoder.

**Comment by merbanan** [comment] 2019-01-13 16:54
So short version in this case I would prefer heuristics based on mean pulse/gap duration as that would keep the working out of the box status.

**Comment by eyJhb** [comment] 2019-01-13 18:15
@merbanan but isn't that just based upon the tolerance/accuracy of the devices?

And could you give a precise example with numbers?
Currently what I am guessing is, that my example has a pulse width of `504 us` and `1480 us`, which added is `1984us`, the difference between that and the first example (`432 us + 1412 us = 1844 us`), is `1984 us-1844 us = 140`, which is different percentage wise (`(100.0/1984)*140=7.05%`). Which should be enough to know the difference between the two?

**Comment by merbanan** [comment] 2019-01-13 18:51
No, you have to differ the short pulse duration in one signal with the other. 504 vs 432 and 1480 vs 1412. Combine that with the fact that pulse period is the same in both signals it gives that the gap duration is 960 vs 1028 in the signals and can be used to solve a relation.

short_pulse_duration -> spd
short_pulse_gap_duration -> spgd

spd + spgd = 1464 us (1) 
s1_spd + s1_spgd = s2_spd + s2_spgd (2)

if we then define a short pulse duration limit as (s1_spd + s2_spd)/2 as spdl we get
spdl = (s1_spd + s2_spd)/2 = (432+504)/2 = 468

and the same for the short pulse gap duration spdgl
spgdl = (s1_spgd + s2_spgd)/2 = (1480+1412)/2 = 1446

if we then compare spd against spdl it will then be lower than the limit and if you then compare the spgd agains the spgdl it must be higher to match one of the signals.

(spd > spdl) and (spgd < spgd) -> signal 1
(spd < spdl) and (spgd < spgd) -> signal 2

We also have the long pulse that fulfills the same type of relation. So depending on how we compare we can adjust the probability of identification. It would be nice with 10 more samples to compare how large the duration distribution is. Right now I just assume it is pretty static.

**Comment by eyJhb** [comment] 2019-01-13 19:07
Makes sense! Would you like to code it yourself, or should I feel free to start if I get the time?
It seems like some underlying code would have to be edited...

I have attached a bunch of more samples!

# Samples
```
root@67644ab293a6:/src/rtl_433/src/samples# ../rtl_433 -S all -R 18
rtl_433 version unknown inputs file rtl_tcp RTL-SDR
Trying conf file at "rtl_433.conf"...
Trying conf file at "/root/.rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Registered 1 out of 120 device decoding protocols [ 18 ]
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sample rate set to 250000 S/s.
Tuner gain set to Auto.
Tuned to 433.920MHz.
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:54:26
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.3 C     Humidity  : 61 %          Integrity : CRC
signal_bsize = 131072  -      sg_index = 2359296
start_pos    = 1877160  -   buffer_size = 3145728
*** Saving signal to file g001_433.92M_250k.cu8
*** Writing data from 1877160, len 131072
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:55:14
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.3 C     Humidity  : 61 %          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:55:14
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.3 C     Humidity  : 61 %          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:55:15
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.3 C     Humidity  : 61 %          Integrity : CRC
signal_bsize = 262144  -      sg_index = 1310720
start_pos    = 692938  -   buffer_size = 3145728
*** Saving signal to file g002_433.92M_250k.cu8
*** Writing data from 692938, len 262144
signal_bsize = 131072  -      sg_index = 2621440
start_pos    = 2158022  -   buffer_size = 3145728
*** Saving signal to file g003_433.92M_250k.cu8
*** Writing data from 2158022, len 131072
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:56:02
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 61 %          Integrity : CRC
signal_bsize = 131072  -      sg_index = 0
start_pos    = 2695444  -   buffer_size = 3145728
*** Saving signal to file g004_433.92M_250k.cu8
*** Writing data from 2695444, len 131072
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:56:50
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 61 %          Integrity : CRC
signal_bsize = 131072  -      sg_index = 2097152
start_pos    = 1531718  -   buffer_size = 3145728
*** Saving signal to file g005_433.92M_250k.cu8
*** Writing data from 1531718, len 131072
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:57:38
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 61 %          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:57:38
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 61 %          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:57:39
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 61 %          Integrity : CRC
signal_bsize = 262144  -      sg_index = 1048576
start_pos    = 347664  -   buffer_size = 3145728
*** Saving signal to file g006_433.92M_250k.cu8
*** Writing data from 347664, len 262144
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:58:26
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 62 %          Integrity : CRC
signal_bsize = 131072  -      sg_index = 2883584
start_pos    = 2351010  -   buffer_size = 3145728
*** Saving signal to file g007_433.92M_250k.cu8
*** Writing data from 2351010, len 131072
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 18:59:14
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 62 %          Integrity : CRC
signal_bsize = 131072  -      sg_index = 1572864
start_pos    = 1187332  -   buffer_size = 3145728
*** Saving signal to file g008_433.92M_250k.cu8
*** Writing data from 1187332, len 131072
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 19:00:02
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 62 %          Integrity : CRC
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 19:00:02
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.4 C     Humidity  : 62 %          Integrity : CRC
signal_bsize = 262144  -      sg_index = 524288
start_pos    = 5076  -   buffer_size = 3145728
*** Saving signal to file g009_433.92M_250k.cu8
*** Writing data from 5076, len 262144
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 19:00:50
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.5 C     Humidity  : 62 %          Integrity : CRC
signal_bsize = 131072  -      sg_index = 2621440
start_pos    = 2004642  -   buffer_size = 3145728
*** Saving signal to file g010_433.92M_250k.cu8
*** Writing data from 2004642, len 131072
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : 2019-01-13 19:02:26
model     : Fine Offset WH5 sensor                 ID        : 7
Temperature: -12.5 C     Humidity  : 62 %          Integrity : CRC
signal_bsize = 262144  -      sg_index = 262144
start_pos    = 2802590  -   buffer_size = 3145728
*** Saving signal to file g011_433.92M_250k.cu8
*** Writing data from 2802590, len 262144
```
[g001_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753394/g001_433.92M_250k.txt)
[g002_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753395/g002_433.92M_250k.txt)
[g003_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753396/g003_433.92M_250k.txt)
[g004_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753397/g004_433.92M_250k.txt)
[g005_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753398/g005_433.92M_250k.txt)
[g006_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753399/g006_433.92M_250k.txt)
[g007_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753400/g007_433.92M_250k.txt)
[g008_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753401/g008_433.92M_250k.txt)
[g009_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753402/g009_433.92M_250k.txt)
[g010_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753403/g010_433.92M_250k.txt)
[g011_433.92M_250k.txt](https://github.com/merbanan/rtl_433/files/2753404/g011_433.92M_250k.txt)

**Comment by merbanan** [comment] 2019-01-13 19:17
I will most likely not have the time to do it in the near future. Feel free to fix it yourself. It would be welcome.

**Comment by merbanan** [comment] 2019-01-13 21:31
Point is that changes in reception might change the pulse lengths produced by the demodulator. So it is not totally sure we can classify the signals properly.

**Comment by eyJhb** [comment] 2019-01-13 21:33
So... Configuration option then?

**Comment by merbanan** [comment] 2019-01-13 21:43
Yeah, I guess. A configuration option is reliable. And it is not that hard to notice that you are 40C wrong.

**Comment by eyJhb** [comment] 2019-01-13 21:49
Exactly. So to keep being backwards conpatible, it should specify the
Rosenborg one to be the "odd" case, right?

**Comment by merbanan** [comment] 2019-01-13 21:53
Yes.

**Comment by zuckschwerdt** [comment] 2019-01-14 06:44
Where would that configuration option be, are you thinking of a compile-time option? Or do we need something like `-R 78:WH5`? Or should this be a different r_device entry?

**Comment by eyJhb** [comment] 2019-01-14 06:51
Compile time would be hell.. Wouldn't it make the most sense to check for a
boolean option in the config? Since it isn't a different decoder (no -R) :)

**Comment by merbanan** [comment] 2019-01-14 15:00
@zuckschwerdt I think a -Q (quirk) wh5_signed_temperature parameter would be nice. And then we could stack the quirks with :.

**Comment by zuckschwerdt** [comment] 2019-01-14 15:16
If the user needs to choose (default / wh5 quirk) why not use the existing scheme of enabling/disabling decoders? The `-R` option is already there. It would be two r_device blocks with a single (the existing) decoder_fn. We already use something like that e.g. for decoders that run on either ASK or FSK.

**Comment by merbanan** [comment] 2019-01-15 11:54
@zuckschwerdt sounds acceptable

**Comment by zuckschwerdt** [comment] 2019-01-26 15:36
Parametric decoders from #960 are merged now. The Rosenborg sensors can be decoded with `rtl_433 -R 18:no-wh5`. This is not the ideal as `wh5` is the real quirk here, but this is backwards-compatible. Maybe we need to change/break this someday to clean up.

**Closed by zuckschwerdt** 2019-01-26 15:36 UTC

**Comment by eyJhb** [comment] 2019-01-31 09:48
@zuckschwerdt  sorry for late acknowledgement, but great work! Thanks for the help! :dolphin: 
I use this software quite a lot, when I am debugging my own implementation of the Rosenborg sensor!

**Comment by zuckschwerdt** [comment] 2026-07-13 20:27
Please note that with #3603 the option to select this decoder is now `-R 356` and not `-R 18:no-wh5` anymore.
