### ISSUE TITLE
Code fails to compile (unknown type name 'uint8_t') ('silvercrest_callback' undeclared here)

### ISSUE THREAD

**Issue by shodanx2** [merbanan/rtl_433#85] opened 2015-01-20 22:29 UTC
Hi,

I'm trying to control etekcity remote controlled outlets (http://goo.gl/gB4jFB), I'm going to use them to control various stuff in my house, lights, blinds, fans, water pump etc.. And also to get input from various security system sensors (beam breakers, magnetic switches, IR sensors, glass break detector etc..)

I tried compiling the software but it fails, here is the console output.

----------------------------------------------------------

-----------------------------------------------------------

motoko build # cmake ../
-- The C compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- checking for module 'libusb-1.0'
--   found libusb-1.0, version 1.0.19
-- Found libusb-1.0: /usr/include/libusb-1.0, /usr/lib64/libusb-1.0.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Udev rules not being installed, install them with -DINSTALL_UDEV_RULES=ON
-- Configuring done
-- Generating done
-- Build files have been written to: /root/rtl_433-master/build

motoko build # make

Scanning dependencies of target rtlsdr_shared
[  3%] Building C object src/CMakeFiles/rtlsdr_shared.dir/librtlsdr.c.o
/root/rtl_433-master/src/librtlsdr.c: In function 'e4000_exit':
/root/rtl_433-master/src/librtlsdr.c:104:22: warning: unused parameter 'dev' [-Wunused-parameter]
 int e4000_exit(void *dev) { return 0; }
                      ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc0012_exit':
/root/rtl_433-master/src/librtlsdr.c:148:23: warning: unused parameter 'dev' [-Wunused-parameter]
 int fc0012_exit(void *dev) { return 0; }
                       ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc0012_set_bw':
/root/rtl_433-master/src/librtlsdr.c:154:25: warning: unused parameter 'dev' [-Wunused-parameter]
 int fc0012_set_bw(void *dev, int bw) { return 0; }
                         ^
/root/rtl_433-master/src/librtlsdr.c:154:34: warning: unused parameter 'bw' [-Wunused-parameter]
 int fc0012_set_bw(void *dev, int bw) { return 0; }
                                  ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc0012_set_gain_mode':
/root/rtl_433-master/src/librtlsdr.c:156:32: warning: unused parameter 'dev' [-Wunused-parameter]
 int fc0012_set_gain_mode(void *dev, int manual) { return 0; }
                                ^
/root/rtl_433-master/src/librtlsdr.c:156:41: warning: unused parameter 'manual' [-Wunused-parameter]
 int fc0012_set_gain_mode(void *dev, int manual) { return 0; }
                                         ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc0013_exit':
/root/rtl_433-master/src/librtlsdr.c:159:23: warning: unused parameter 'dev' [-Wunused-parameter]
 int fc0013_exit(void *dev) { return 0; }
                       ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc0013_set_bw':
/root/rtl_433-master/src/librtlsdr.c:163:25: warning: unused parameter 'dev' [-Wunused-parameter]
 int fc0013_set_bw(void *dev, int bw) { return 0; }
                         ^
/root/rtl_433-master/src/librtlsdr.c:163:34: warning: unused parameter 'bw' [-Wunused-parameter]
 int fc0013_set_bw(void *dev, int bw) { return 0; }
                                  ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc2580_exit':
/root/rtl_433-master/src/librtlsdr.c:167:23: warning: unused parameter 'dev' [-Wunused-parameter]
 int fc2580_exit(void *dev) { return 0; }
                       ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc2580_set_bw':
/root/rtl_433-master/src/librtlsdr.c:171:34: warning: unused parameter 'bw' [-Wunused-parameter]
 int fc2580_set_bw(void *dev, int bw) { return fc2580_SetBandwidthMode(dev, 1); }
                                  ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc2580_set_gain':
/root/rtl_433-master/src/librtlsdr.c:172:27: warning: unused parameter 'dev' [-Wunused-parameter]
 int fc2580_set_gain(void *dev, int gain) { return 0; }
                           ^
/root/rtl_433-master/src/librtlsdr.c:172:36: warning: unused parameter 'gain' [-Wunused-parameter]
 int fc2580_set_gain(void *dev, int gain) { return 0; }
                                    ^
/root/rtl_433-master/src/librtlsdr.c: In function 'fc2580_set_gain_mode':
/root/rtl_433-master/src/librtlsdr.c:173:32: warning: unused parameter 'dev' [-Wunused-parameter]
 int fc2580_set_gain_mode(void *dev, int manual) { return 0; }
                                ^
/root/rtl_433-master/src/librtlsdr.c:173:41: warning: unused parameter 'manual' [-Wunused-parameter]
 int fc2580_set_gain_mode(void *dev, int manual) { return 0; }
                                         ^
/root/rtl_433-master/src/librtlsdr.c: In function 'r820t_exit':
/root/rtl_433-master/src/librtlsdr.c:180:22: warning: unused parameter 'dev' [-Wunused-parameter]
 int r820t_exit(void *dev) { return 0; }
                      ^
/root/rtl_433-master/src/librtlsdr.c: In function 'r820t_set_bw':
/root/rtl_433-master/src/librtlsdr.c:182:24: warning: unused parameter 'dev' [-Wunused-parameter]
 int r820t_set_bw(void *dev, int bw) { return 0; }
                        ^
/root/rtl_433-master/src/librtlsdr.c:182:33: warning: unused parameter 'bw' [-Wunused-parameter]
 int r820t_set_bw(void *dev, int bw) { return 0; }
                                 ^
[  6%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_e4k.c.o
[  9%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc0012.c.o
[ 12%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc0013.c.o
[ 15%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_fc2580.c.o
/root/rtl_433-master/src/tuner_fc2580.c: In function 'fc2580_wait_msec':
/root/rtl_433-master/src/tuner_fc2580.c:124:29: warning: unused parameter 'pTuner' [-Wunused-parameter]
 void fc2580_wait_msec(void *pTuner, int a)
                             ^
/root/rtl_433-master/src/tuner_fc2580.c:124:41: warning: unused parameter 'a' [-Wunused-parameter]
 void fc2580_wait_msec(void *pTuner, int a)
                                         ^
[ 18%] Building C object src/CMakeFiles/rtlsdr_shared.dir/tuner_r820t.c.o
/root/rtl_433-master/src/tuner_r820t.c: In function 'R828_Delay_MS':
/root/rtl_433-master/src/tuner_r820t.c:207:8: warning: unused parameter 'pTuner' [-Wunused-parameter]
  void *pTuner,
        ^
/root/rtl_433-master/src/tuner_r820t.c:208:16: warning: unused parameter 'WaitTimeMs' [-Wunused-parameter]
  unsigned long WaitTimeMs
                ^
/root/rtl_433-master/src/tuner_r820t.c: In function 'R828_Filt_Cal':
/root/rtl_433-master/src/tuner_r820t.c:2484:66: warning: unused parameter 'R828_BW' [-Wunused-parameter]
 R828_ErrCode R828_Filt_Cal(void *pTuner, UINT32 Cal_Freq,BW_Type R828_BW)
                                                                  ^
Linking C shared library librtlsdr.so
[ 18%] Built target rtlsdr_shared
Scanning dependencies of target rtl_433
[ 21%] Building C object src/CMakeFiles/rtl_433.dir/rtl_433.c.o
/root/rtl_433-master/src/rtl_433.c: In function 'debug_callback':
/root/rtl_433-master/src/rtl_433.c:40:66: warning: unused parameter 'bits_per_row' [-Wunused-parameter]
 int debug_callback(uint8_t bb[BITBUF_ROWS][BITBUF_COLS], int16_t bits_per_row[BITBUF_ROWS]) {
                                                                  ^
/root/rtl_433-master/src/rtl_433.c: In function 'sighandler':
/root/rtl_433-master/src/rtl_433.c:185:28: warning: unused parameter 'signum' [-Wunused-parameter]
 static void sighandler(int signum) {
                            ^
[ 25%] Building C object src/CMakeFiles/rtl_433.dir/devices/silvercrest.c.o
In file included from /root/rtl_433-master/src/devices/silvercrest.c:1:0:
/root/rtl_433-master/include/rtl_433.h:48:30: error: unknown type name 'uint8_t'
     int     (*json_callback)(uint8_t bits_buffer[BITBUF_ROWS][BITBUF_COLS],int16_t bits_per_row[BITBUF_ROWS]) ;
                              ^
/root/rtl_433-master/include/rtl_433.h:49:1: warning: no semicolon at end of struct or union [enabled by default]
 } r_device;
 ^
/root/rtl_433-master/include/rtl_433.h:52:20: error: unknown type name 'uint8_t'
 int debug_callback(uint8_t buffer[BITBUF_ROWS][BITBUF_COLS], int16_t bits_per_row[BITBUF_ROWS]);
                    ^
/root/rtl_433-master/src/devices/silvercrest.c:3:33: error: unknown type name 'uint8_t'
 static int silvercrest_callback(uint8_t bb[BITBUF_ROWS][BITBUF_COLS],int16_t bits_per_row[BITBUF_ROWS]) {
                                 ^
/root/rtl_433-master/src/devices/silvercrest.c:33:30: error: 'silvercrest_callback' undeclared here (not in a function)
     /* .json_callback  = */ &silvercrest_callback,
                              ^
/root/rtl_433-master/src/devices/silvercrest.c:33:29: warning: excess elements in struct initializer [enabled by default]
     /* .json_callback  = */ &silvercrest_callback,
                             ^
/root/rtl_433-master/src/devices/silvercrest.c:33:29: warning: (near initialization for 'silvercrest') [enabled by default]
src/CMakeFiles/rtl_433.dir/build.make:80: recipe for target 'src/CMakeFiles/rtl_433.dir/devices/silvercrest.c.o' failed
make[2]: *** [src/CMakeFiles/rtl_433.dir/devices/silvercrest.c.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'src/CMakeFiles/rtl_433.dir/all' failed
make[1]: *** [src/CMakeFiles/rtl_433.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by helgew** [comment] 2015-01-20 22:33
This is a duplicate of #76 and a pull request with the fix has been submitted as part of pull request #82. For now, you can add '#include <stdint.h>' in include/rtl_433.h to fix the problem.

**Comment by shodanx2** [comment] 2015-01-20 22:40
Added

#include <stdint.h>

to rtl_433-master/include/rtl_433.h and now it compiled successfully !

[100%] Built target rtlsdr_static

thanks !



On Tue, Jan 20, 2015 at 5:33 PM, Helge Weissig <notifications@github.com>
wrote:

> This is a duplicate of #76 <https://github.com/merbanan/rtl_433/issues/76>
> and a pull request with the fix has been submitted as part of pull request
> #82 <https://github.com/merbanan/rtl_433/pull/82>. For now, you can add
> '#include ' in include/rtl_433.h to fix the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/merbanan/rtl_433/issues/85#issuecomment-70748393>.
>



-- 
Jean-Francois Perreault
Professional geek

Inanimate objects can be classified scientifically into three major
categories;
those that don't work, those that break down and those that get lost.
-*Russell Baker *

"It ain't what you don't know that gets you into trouble. It's what you
know for sure that just ain't so."
-* Mark **Twain*

Computers are like Old Testament gods; lots of rules and no mercy.

- *Joseph Campbell*

**Comment by shodanx2** [comment] 2015-01-20 22:48
And it totally works 

*** signal_start = 56791174, signal_end = 56876103
signal_len = 84929,  pulses = 275
Iteration 1. t: 96    min: 44 (190)    max: 149 (85)    delta 61
Iteration 2. t: 96    min: 44 (190)    max: 149 (85)    delta 0
Pulse coding: Short pulse length 44 - Long pulse length 149

Short distance: 35, long distance: 145, packet distance: 1463

p_limit: 96

[00] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[01] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[02] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[03] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[04] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[05] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[06] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[07] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[08] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[09] {25} 05 17 03 00 : 00000101 00010111 00000011 00000000
[10] {25} 05 15 00 00 : 00000101 00010101 00000000 00000000





*** signal_start = 58143679, signal_end = 58228599
signal_len = 84920,  pulses = 275
Iteration 1. t: 93    min: 41 (190)    max: 146 (85)    delta 61
Iteration 2. t: 93    min: 41 (190)    max: 146 (85)    delta 0
Pulse coding: Short pulse length 41 - Long pulse length 146

Short distance: 38, long distance: 148, packet distance: 1468

p_limit: 93

[00] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[01] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[02] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[03] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[04] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[05] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[06] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[07] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[08] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[09] {25} 05 17 0c 00 : 00000101 00010111 00001100 00000000
[10] {25} 05 15 00 00 : 00000101 00010101 00000000 00000000

**Comment by helgew** [comment] 2015-01-20 23:04
Awesome!

Would you mind closing the issue?

**Closed** 2015-01-20 23:07 UTC

**Comment by shodanx2** [comment] 2015-01-20 23:12
Is there a place to post the results I have with various 433 mhz devices and rtl_433 ?
I could also make scope traces of the transmitters with circuit pictures etc..
